CREATE SCHEMA IF NOT EXISTS randomdata;

CREATE TABLE NAME (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(20) UNIQUE,
    compuesto BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE ITEM (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(40) UNIQUE,
    price NUMERIC,
    taxtype INT
);

CREATE TABLE DNI (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    number INT UNIQUE,
    character VARCHAR(1),
    used BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE PERSON (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    nameid INT,
    dniid INT,
    age INT,
    CONSTRAINT FK_NAMEID FOREIGN KEY (nameid) REFERENCES NAME(ID),
    CONSTRAINT FK_DNIID FOREIGN KEY (dniid) REFERENCES DNI(ID),
    CONSTRAINT UNIQUE_DNIID UNIQUE (dniid)
);