spring:
  application:
    name: name-splitter
  kafka:
    bootstrap-servers: localhost:9092

schema:
  registry:
    url: http://localhost:8081

topics:
  person: person-topic
  name-composed: name-composed-topic
  name-simple: name-simple-topic
  login: login-topic

logging:
  level:
    com.gumi.cursos.kstream.namesplitter: DEBUG
    root: INFO