server:
  servlet:
    context-path: /random-data

spring:
  kafka:
    bootstrap-servers: localhost:9092
  flyway:
    enabled: true
    locations: classpath:/db/migration
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      schema: randomdata
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    continue-on-error: false

schema:
  registry:
    url: http://localhost:8081

topics:
  person: person-topic

logging:
  level:
    org.springframework: INFO
    com.gumi.cursos.kstream.randomdata: DEBUG